repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.0
    hooks:
      - id: ruff
        args: [--fix]
        stages: [commit]
      - id: ruff-format
        stages: [commit]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-merge-conflict

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.9.0
    hooks:
      - id: eslint
        stages: [commit]
        files: ^frontend/
        types: [javascript, jsx]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.3.3
    hooks:
      - id: prettier
        stages: [commit]
        files: ^frontend/

ci:
  autofix_commit_msg: "ci: auto fixes from pre-commit hooks"
  autofix_prs: true
  autoupdate_branch: ''
  autoupdate_commit_msg: 'ci: update pre-commit hooks'
  autoupdate_schedule: weekly
  skip: [eslint, prettier]  # Skip linters that require node_modules in CI
  submodules: false
