services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fastapi-backend
    environment:
      - ENVIRONMENT=development
      - APP_NAME=${APP_NAME:-FastAPI Boilerplate}
      - API_V1_PREFIX=${API_V1_PREFIX:-/api/v1}
      - BACKEND_CORS_ORIGINS=${BACKEND_CORS_ORIGINS:-http://localhost:5173}
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/workspace/backend
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react-frontend
    depends_on:
      - backend
    environment:
      - VITE_API_BASE_PATH=${VITE_API_BASE_PATH:-/api}
      - VITE_API_VERSION=${VITE_API_VERSION:-v1}
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
